import type { Metadata } from "next";
import { Bebas_Neue, Orbitron } from "next/font/google";
import "./globals.css";


const bebasneue = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebasneue",
  display: "swap",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-orbitron",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Organizador Financeiro",
  description: "Generated by GHats",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${orbitron.variable} ${bebasneue.variable} antialiased`}
      >

           <header>
            <nav className="topo">
                <li>
                    <label>Reserva</label>
                    <label>Home</label>
                    <label>Patrimônio</label>
                </li>
            </nav> 
        </header>

        {children}
      </body>
    </html>
  );
}
